### ISSUE TITLE
distinctOn and Embedded

### ISSUE THREAD

**Issue by DGolubets** [zio/zio-protoquill#158]
`distinctOn' doesn't generate proper SQL when used with embedded classes.

E. g. `distinctOn(_.emb.id)` generates `DISTINCT ON (a.id)` instead of `DISTINCT ON (a.embid)` so the query fails at runtime with `column does not exist`.

As a workaround I just use `.distinctOn(_ => infix"embid")`

**Comment by deusaquilus** [comment]
@DGolubets I think this is the same as https://github.com/zio/zio-quill/issues/2556 which was fixed in https://github.com/zio/zio-quill/pull/2583 and released with 4.4.0. Could you please double-check if it's still happening?

**Comment by guizmaii** [comment]
Closing as no answer. @DGolubets Could you tell us if `v4.4.0` fixed this issue, please?
