### ISSUE TITLE
import ctx.jsonb.* does not work

### ISSUE THREAD

**Issue by lachezar** [zio/zio-protoquill#206]
I use Scala 3.2, ZIO 2.0.1 with Quill 4.6.0, however when I try to import `json` or `jsonb` I get error that such 
```
value jsonb is not a member of io.getquill.PostgresZioJdbcContext[com.rocker.quill.CustomQuillNamingStrategy.type], but could be made available as an extension method
```

However I can still wrap my db fields with `JsonbValue` and manually encode/decode to it.

**Comment by guizmaii** [comment]
Why do you need to import `jsonb` from your context?

Closing as it doesn't seem to be something that Quill offers

**Comment by lachezar** [comment]
The simple answer is because the example in the docs do that:
https://github.com/zio/zio-quill/pull/2615/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R3451

**Comment by guizmaii** [comment]
It's apparently not anymore in the doc: https://zio.dev/zio-quill/contexts/#json
