### ISSUE TITLE
Quill 3.x Artifact not published for 4.6.1

### ISSUE THREAD

**Issue by tOverney** [zio/zio-protoquill#309]
Hi hi,

Looking at the Github releases there seem to be a 4.6.1 release attempt at the end of July:
https://github.com/zio/zio-protoquill/releases/tag/v4.6.1

But going on Maven central to https://mvnrepository.com/artifact/io.getquill/quill-jdbc or https://mvnrepository.com/artifact/io.getquill/quill-sql
there's no 3.x artefact available for 4.6.1

Thank you in advance,
Best,
- Tristan

@zio-protoquill/maintainers

**Comment by juliano** [comment]
Hi @tOverney,

We had some problems with the build and release process. It's fixed now, please use [the version 4.7.0, published today](https://github.com/zio/zio-protoquill/releases/tag/v4.7.0).

Thank you for you patience.
