### ISSUE TITLE
Using flilter + lift together with Insert Fails

### ISSUE THREAD

**Issue by fomkin** [zio/zio-protoquill#37]
**Version**: `v3.10.0.Beta1.6`
**Module**: `quill-jasync-postgres`
**Database**: `postgres`
**Scala**: 3.1.0

```scala
inline def updateAccount = 
  query[Account]
    .filter(a => a.id == lift(account.id))
    .update(lift(account))
run(updateAccount)
```

### Expected behavior

Code compiles.

### Actual behavior

Compile time error:
```
[error]    |Invalid Transformations Encountered. Cannot find lift with ID: 5883cb8e-d883-4b0f-8944-679f9058fa44.
[error]    | This location contains code that was inlined from AccountRepositoryImpl.scala:42
[error]    | This location contains code that was inlined from Context.scala:167
```
Selecting, inserting and deleting compiles and works fine.
Also I tried to rewrite this with lazyLift and got:
```
Parsed Insert Macro AST is not a Case Class: 
ScalarTag("2d97b8c1-5872-47b3-9213-52c107e065ff") (or a batch-query Ident).
```
BUT it is update operation, not insert.
When I removing filter compilation begin to pass, but it is not I want.

### Workaround

```scala
      query[Account]
        .insert(lift(account))
        .onConflictUpdate(_.id)(
          (t, e) => t.updated -> e.updated,
          (t, e) => t.nickname -> e.nickname,
          (t, e) => t.email -> e.email,
          (t, e) => t.passwordHash -> e.passwordHash
        )
```

@deusaquilus

**Comment by deusaquilus** [comment]
Whoops, I did not consider lifts in the final inner-entity expander. Will have a look at this soon.

**Comment by kimmoeklund** [comment]
I have same problem with `postgres` and `"quill-jdbc" % "3.12.0.Beta1.7"`
