### ISSUE TITLE
Could not serialize the 'class io.getquill.ast.Insert' when compiling in Linux + Java 17

### ISSUE THREAD

**Issue by dgeyer** [zio/zio-protoquill#51]
Getting the error `Could not serialize the 'class io.getquill.ast.Insert'` when compiling a project using Linux + Java 17 
MacOS + Java 17 compiles 

**Version**: 3.12.0.Beta1.7

### Expected behavior 
Project should compile

### Actual behavior
Getting warnings and errors:
`11 27.77 [error] -- Error: /usr/src/my_workdir/src/main/scala/QuillHelper.scala:26:29 -----------
#11 27.77 [error] 26 |      r <- ctx.run(dummyQuote(dummy))
#11 27.77 [error]    |                   ^^^^^^^^^^^^^^^^^
#11 27.78 [error]    |   Could not serialize the 'class io.getquill.ast.Insert' Insert(
#11 27.78 [error]    |     query = Entity("DummyClass", List()),
#11 27.78 [error]    |     assignments = List(
#11 27.78 [error]    |       Assignment(
#11 27.78 [error]    |         alias = Id("_$V"),
#11 27.78 [error]    |         property = Property(ast = Id("_$V"), name = "dummy0"),
#11 27.78 [error]    |         value = ScalarTag(uid = "dc2f1c36-ea87-4df1-975c-2b7d0969d7da")
#11 27.78 [error]    |       ),
#11 27.78 [error]    |       Assignment(
#11 27.78 [error]    |         alias = Id("_$V"),
#11 27.79 [error]    |         property = Property(ast = Id("_$V"), name = "dummy1"),
#11 27.79 [error]    |         value = ScalarTag(uid = "fda8f904-8dfb-417e-8a82-13268067ca3f")
#11 27.79 [error]    |       ),
#11 27.79 [error]    |       Assignment(
#11 27.79 [error]    |         alias = Id("_$V"),
#11 27.79 [error]    |         property = Property(ast = Id("_$V"), name = "dummy2"),
#11 27.79 [error]    |         value = ScalarTag(uid = "ca9aa277-1256-49ec-b171-096890f82770")
#11 27.79 [error]    |       ),
#11 27.79 [error]    |       Assignment(
#11 27.79 [error]    |         alias = Id("_$V"),
#11 27.79 [error]    |         property = Property(ast = Id("_$V"), name = "dummy3"),
#11 27.80 [error]    |         value = ScalarTag(uid = "c5cc218a-974a-4454-98fa-de592e18c361")
#11 27.80 [error]    |       ),
#11 27.80 [error]    |       Assignment(
#11 27.80 [error]    |         alias = Id("_$V"),
#11 27.80 [error]    |         property = Property(ast = Id("_$V"), name = "dummy4"),
#11 27.80 [error]    |         value = ScalarTag(uid = "819960e6-3e3b-43b1-b398-51fdbe99c8fe")
#11 27.80 [error]    |       )
#11 27.80 [error]    |     )
#11 27.80 [error]    |   ).
#11 27.80 [error]    | This location contains code that was inlined from QuillHelper.scala:26
#11 27.80 [error]    | This location contains code that was inlined from GetQuill.scala:3
#11 27.81 [error]    | This location contains code that was inlined from QuillHelper.scala:15`

### Steps to reproduce the behavior
I have created a sample project with a dockerfile to reproduce the error:
Clone the sample project: https://github.com/dgeyer/dummy-proto-quill-use
Run `docker build .`

### Workaround

@getquill/maintainers

**Comment by deusaquilus** [comment]
I think I need to replace the serialization since the twitter Chill library doesn't seem to be solving this issue. Sorry about the headaches.

**Comment by deusaquilus** [comment]
Merged a change to fix this in #72. Going to do a release and try it out.
