### ISSUE TITLE
Parameter used outside the scope where it was defined

### ISSUE THREAD

**Issue by ajrnz** [zio/zio-protoquill#85]
**Version**: 3.17.0.Beta3.0-RC2
**Module**: `quill-jdbc`
**Database**: postgres

```scala
case class TestClass(info: String, recorded: Instant)

object QuillTest {
  val ctx = new PostgresJdbcContext(SnakeCase, "test")
  import ctx._

  implicit val instantEncoder: MappedEncoding[Instant, Date] = MappedEncoding[Instant, Date](i => Date.from(i))
  implicit val instantDecoder: MappedEncoding[Date, Instant] = MappedEncoding[Date, Instant](d => d.toInstant)

  implicit class DateComparison(left: Instant) {
    def >(right: Instant) = quote(infix"$left > $right".as[Boolean])
  }

  val startDate =
    LocalDateTime.parse("2022-02-01T00:00:00").atZone(ZoneOffset.UTC).toInstant

  inline def testQ = query[TestClass].filter(r => r.recorded > lift(startDate))
  val items = ctx.run(testQ)
}
```

### Expected behavior

Compiles and runs

### Actual behavior

results in:

    [error] -- Error: /Users/ajr/qt/QuillTest.scala:28:22 
    [error] 28 |  val items = ctx.run(testQ)
    [error]    |                      ^^^^^
    [error]    |While expanding a macro, a reference to parameter r was used outside the scope where it was defined
    [error]    | This location contains code that was inlined from QuillTest.scala:27
    [error]    | This location contains code that was inlined from GetQuill.scala:3
    [info] -- Info: /Users/ajr/qt/QuillTest.scala:28:21 
    [info] 28 |  val items = ctx.run(testQ)
    [info]    |              ^^^^^^^^^^^^^^
    [info]    |              Dynamic Query Detected
    [error] one error found
    [error] one error found
    1 targets failed

### Steps to reproduce the behavior

Compile the above.

Contrast with the non-scala3 version which works: [scala 2.13 example](https://scastie.scala-lang.org/ajrnz/lb25i49eT169MKiv1FS33g/4)

@getquill/maintainers

**Comment by deusaquilus** [comment]
@ajrnz Please try:
```scala
  extension (inline left: Instant) {
    inline def >(right: Instant) = quote(infix"$left > $right".as[Boolean])
  }
```
The implicit-class extension pattern should work in Dotty but should be a dynamic query.
Use inline extension methods instead. I have a TODO to at least check for this pattern in the parser and report on what to do.

**Comment by ajrnz** [comment]
Doh. It was originally an extension but I converted it to an implicit class to check if it worked in 2.13.

The key change was `inline` which makes it work and is understandable in retrospect.

Some kind of nudge to the user to check for missing inlines in this case might be nice.

Thanks for the quick reply.

**Comment by deusaquilus** [comment]
> Some kind of nudge to the user to check for missing inlines in this case might be nice.

Yeah, I'm thinking about how to detect this in the parser. Maybe looking for variables with the name `proxy$...` might work. Something I need to investigate.
